amazon_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('users/',include('custom_user.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('',views.index, name='index'),
    path('cart/',views.cart, name='cart'),
    path('search/', views.search, name= 'search'),
    path('checkout/',views.checkout, name="checkout"),
    path('update_item/', views.updateItem,name='update_item'),
    path('process_order/', views.processOrder,name='process_order'),
    path('contact_us/', views.contact_us,name='contact_us'),
    path('favourite/', views.favourite,name='favourite'),
    path('contact_me/',views.contact_me,name='contact_me'),
    path('about/',views.about,name='about'),
    path('our_service/',views.our_service,name='our_service'),
    path('detail_of/<str:str>', views.detail,name='detail'),
    # path('add-to-cart/<int:product_id>/',views.add_to_cart,name='add_to_cart')
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True,blank=True)
    name =models.CharField(max_length=200, null=True)
    email=models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=200,null=True)
    appearance = models.CharField(max_length=100,null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True,blank=False)
    image = models.ImageField(null=True,blank=True)
    star = models.ImageField(null=True,blank=True)
    rating = models.FloatField()
    available = models.BooleanField(default=True, null=True,blank=False)
    category = models.CharField(max_length=100,null=True)
    description = models.TextField(max_length=700,null=True)


    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
    @property
    def starURL(self):
        try:
            url = self.star.url
        except:
            url = ''
        return url

class Order(models.Model):
    transaction_id = models.CharField(max_length=80,null=True)
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False,null=True,blank=False)

    def __str__(self) -> str:
        return str(self.id)
    
    # @property
    # def shipping(self):
    #     shipping = False
    #     orderitems = self.orderitem_set.all()
    #     for i in orderitems:
    #         if i.product.digital == False:
    #             shipping == True
    #     return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    

class OrderItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL, blank=True, null=True)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    username = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    region = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    payment_method = models.CharField(max_length=200, null=True)
    name_card = models.CharField(max_length=100,null=True)
    card_number = models.IntegerField(null=True)
    expiration = models.CharField(max_length=90,null=True)
    cvv = models.CharField(max_length=90,null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username
    

class Contact_us(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, blank=True, null=True)
    full_name = models.CharField(max_length=100,null=True)
    email_address = models.CharField(max_length=100,null=True)
    mobile = models.CharField(max_length=100,null=True)
    email_subject = models.CharField(max_length=100,null=True)
    messasge_info = models.CharField(max_length=100,null=True)

products/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import *
from django.http import JsonResponse
import json
import datetime
# Create your views here.

def index(request):
    
    # jUST ADDed
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items

    else:
        items = []
        order = {'get_cart_total': 0,'get_cart_items': 0,'shipping':False}
        cartItems = order['get_cart_items']

    products = Product.objects.all()
    context = {'products':products,'cartItems':cartItems,'items':items}
    return render(request,'product_page/index.html',context) 

# def checkout(request):
#     return render(request, 'product_page/checkout.html')
@login_required(login_url='/users/login/')
def search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        products = Product.objects.filter(name__contains=searched)
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
        return render(request, 'product_page/search_product.html',{'searched':searched,'products':products,'cartItems':cartItems})
        
    else:
        return render(request, 'product_page/search_product.html',{})


def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
        
    else:
        items = []
        order = {'get_cart_total': 0,'get_cart_items': 0,'shipping':False}
        cartItems = order['get_cart_items']
    
    context = {'items': items, 'order':order,'cartItems':cartItems }
    return render(request, 'product_page/cart.html',context)

@login_required(login_url='/users/login/')
def checkout(request):
    
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items

    else:
        items = []
        order = {'get_cart_total': 0,'get_cart_items': 0,'shipping':False}
        cartItems = order['get_cart_items']

    # receiving checkout form
    
    context = {'items': items, 'order':order,'cartItems':cartItems}
    return render(request,'product_page/checkout.html',context)

@login_required(login_url='/users/login/')
def favourite(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0,'get_cart_items': 0,'shipping':False}
        cartItems = order['get_cart_items']
        
    context = {'items': items, 'order':order,'cartItems':cartItems}
    return render(request, 'product_page/favourite.html',context)

def detail(request, str):
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0,'get_cart_items': 0,'shipping':False}
        cartItems = order['get_cart_items']
    
    product = Product.objects.get(name=str)
    related_product = Product.objects.filter(category=product.category).exclude(name=product.name)[:4]
    context = {'product':product,'cartItems':cartItems,'items':items,'related':related_product}
    return render(request, 'product_page/detail.html',context)

def contact_me(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0,'get_cart_items': 0,'shipping':False}
        cartItems = order['get_cart_items']
        
    context = {'items': items, 'order':order,'cartItems':cartItems}
    return render(request,'product_page/contact_me.html',context)


def our_service(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0,'get_cart_items': 0,'shipping':False}
        cartItems = order['get_cart_items']
        
    context = {'items': items, 'order':order,'cartItems':cartItems}
    return render(request,'product_page/our_service.html',context)


def about(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0,'get_cart_items': 0,'shipping':False}
        cartItems = order['get_cart_items']
        
    context = {'items': items, 'order':order,'cartItems':cartItems}
    return render(request,'product_page/about.html',context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('Action:',action)
    print('productId: ', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order,created = Order.objects.get_or_create(customer=customer,complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order,product=product)

    
    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    elif action == 'delete':
        orderItem.quantity = 0

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == order.get_cart_total:
            order.complete = True
        order.save()

        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            first_name = data['shipping']['first_name'],
            last_name = data['shipping']['last_name'],
            username = data['shipping']['username'],
            email = data['shipping']['email'],
            address = data['shipping']['address'],
            city = data['shipping']['region'],
            zipcode = data['shipping']['zip'],
            payment_method = data['shipping']['payment_method'],
            name_card = data['shipping']['name_card'],
            card_number = data['shipping']['card_number'],
            expiration = data['shipping']['expiration'],
            cvv = data['shipping']['cvv'],

        )
        
    return JsonResponse('payment complete', safe=False)

def contact_us(request):
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer

        Contact_us.objects.create(
            customer=customer,
            full_name=data['contact_us']['full_name'],
            email_address=data['contact_us']['email_address'],
            mobile=data['contact_us']['mobile'],
            email_subject=data['contact_us']['email_subject'],
            messasge_info=data['contact_us']['message']
        )

    return JsonResponse('message successful', safe=False)

products/templates/product_page/about.html
{% extends "layout.html" %}
{% load static %}

{% block title %}{% endblock  %}

{% block unique %}
<link href="http://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'styles/portfolio.css' %}">
{% endblock  %}

{% block content %}


<!-- home section design-->
<section class="home" id="home">

    <div class="home-content">
        <h3>Hello, It's me</h3>
        <h1>Fordjour Jones Michael</h1>
        <h3>And I'm a <span class="multiple-text"></span></h3>
        <p>Amazon is the leading in digital marketing around the globe with
            quality and quantity sales of products. We have everything to offer you ,
            you just ask for it. Our products are affordable and of high standard.
            If you have any question you <a style="color:orange;" href="{% url 'products:contact_me' %}">contact us</a>.Thank you
        </p>
        <div class="social-media">
            <a href="#"><i class="bx bxl-facebook"></i></a>
            <a href="#"><i class="bx bxl-twitter"></i></a>
            <a href="#"><i class="bx bxl-instagram-alt"></i></a>
            <a href="#"><i class="bx bxl-linkedin"></i></a>
        </div>
        <a href="" class="btn" onclick="download()">Download</a>
    </div>

    <div class="home-img">
        <div class="hexagon">
            <img src="{% static 'images/profile_pic.jpeg' %}" alt="" width="100px" height="300px">
        </div>
    </div>

</section>

<!-- about section design -->

<section class="about" id="about">
    <div class="about-img">
        <img src="{% static 'images/profile_pic.jpeg' %}" alt="profile picture" height="300px">
    </div>

    <div class="about-content">
        <h2 class="heading">About <span>Me</span></h2>
        <h3>Web Developer!</h3>
        <p>Amazon is the leading in digital marketing around the globe with
            quality and quantity sales of products. We have everything to offer you ,
            you just ask for it. Our products are affordable and of high standard.
            If you have any question you <a style="color:orange;" href="{% url 'products:contact_me' %}">contact us</a>.Thank you</p>
        <a href="#" class="btn">Read More</a>
    </div>
</section>

{% endblock  %}

products/templates/product_page/cart.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Checkout</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/styles/shared/general.css">
    <link rel="stylesheet" href="/static/styles/pages/checkout/checkout-header.css">
    <link rel="stylesheet" href="/static/styles/pages/checkout/checkout.css">
    <script type='text/javascript'>var user = '{{request.user}}'
      function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
      }
      let csrftoken = getToken('csrftoken');
  </script>
  </head>
  <body>
    <div class="checkout-header">
      <div class="header-content">
        <div class="checkout-header-left-section">
          <a href="{% url "products:index" %}">
            <img class="amazon-logo" src="{% static 'images/amazon-logo.png' %}">
            <img class="amazon-mobile-logo" src="{% static 'images/amazon-mobile-logo.png' %}">
          </a>
        </div>

        <div class="checkout-header-middle-section">
          Checkout (<a class="return-to-home-link"
            href="{% url 'products:index' %}">{{order.get_cart_items}} items</a>)
        </div>

        <div class="checkout-header-right-section">
          <img src="{% static 'images/icons/checkout-lock-icon.png' %}">
        </div>
      </div>
    </div>

    <div class="main">
      <div class="page-title">Review your order</div>

      <div class="checkout-grid">
        <div class="order-summary">
  
          {% for item in items %}
          <div class="cart-item-container">
            <div class="delivery-date">
              Delivery date: {{item.date_added}}
            </div>

            <div class="cart-item-details-grid">
              <img class="product-image"
                src="{{item.product.imageURL}}">

              <div class="cart-item-details">
                <div class="product-name">
                  {{item.product.name}}
                </div>
                <div class="product-price">
                  ${{item.product.price|floatformat:2}}
                </div>
                <div class="product-price">
                  Total: ${{item.get_total|floatformat:2}}
                </div>
                <div class="product-quantity">
                  <span>
                    Quantity: <span class="quantity-label">{{item.quantity}}</span>
                  </span>
                  <span data-product={{item.product.id}} data-action="add" class="update-quantity-link link-primary update-cart"  style="user-select: none;">
                    Increase
                  </span>
                  <span  data-product={{item.product.id}} data-action="remove" class="delete-quantity-link link-primary update-cart"  style="user-select: none;">
                    Decrease
                  </span>
                  <span  data-product={{item.product.id}} data-action="delete" class="delete-quantity-link link-primary update-cart"  style="user-select: none;">
                    Delete
                  </span>
                </div>
              </div>

              <div class="delivery-options">
                <div class="delivery-options-title">
                  Choose a delivery option:
                </div>

                <div class="delivery-option">
                  <input type="radio" class="delivery-option-input"
                    name="delivery-option-2">
                  <div>
                    <div class="delivery-option-date">
                      Tuesday, June 21
                    </div>
                    <div class="delivery-option-price">
                      FREE Shipping
                    </div>
                  </div>
                </div>
                <div class="delivery-option">
                  <input type="radio" checked class="delivery-option-input"
                    name="delivery-option-2">
                  <div>
                    <div class="delivery-option-date">
                      Wednesday, June 15
                    </div>
                    <div class="delivery-option-price">
                      $4.99 - Shipping
                    </div>
                  </div>
                </div>
                <div class="delivery-option">
                  <input type="radio" class="delivery-option-input"
                    name="delivery-option-2">
                  <div>
                    <div class="delivery-option-date">
                      Monday, June 13
                    </div>
                    <div class="delivery-option-price">
                      $9.99 - Shipping
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

        <div class="payment-summary">
          <div class="payment-summary-title">
            Order Summary
          </div>

          <div class="payment-summary-row">
            <div>Items ({{order.get_cart_items}}):</div>
            <div class="payment-summary-money">${{order.get_cart_total|floatformat:2}}</div>
          </div>

          <div class="payment-summary-row">
            <div>Shipping &amp; handling:</div>
            <div class="payment-summary-money">$0.00</div>
          </div>

          <div class="payment-summary-row subtotal-row">
            <div>Total before tax:</div>
            <div class="payment-summary-money">${{order.get_cart_total|floatformat:2}}</div>
          </div>

          <div class="payment-summary-row">
            <div>Estimated tax (0%):</div>
            <div class="payment-summary-money">$0.00</div>
          </div>

          <div class="payment-summary-row total-row">
            <div>Order total:</div>
            <div class="payment-summary-money">${{order.get_cart_total|floatformat:2}}</div>
          </div>

          <button class="place-order-button button-primary">
            <a href="{% url 'products:checkout' %}">Place your order</a>
          </button>
          
        </div>
      </div>
      <script type="text/javascript" src="{% static 'scripts/cart.js' %}"></script>
    </div>
  </body>
</html>

products/templates/product_page/detail.html
{% extends "layout.html" %}

{% block title %}Amazon Detail{% endblock  %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/detail_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
{% endblock  %}

{% block content %}
<br><br><br>
<div class = "card-wrapp">
    <div class = "cards">
      <!-- card left -->
      <div class = "product-imgs">
        <div class = "img-display">
          <div class = "img-showcase">
            <img  src = "{{product.imageURL}}" alt = "shoe image">
          </div>
        </div>
        <br>
        <p style="font-size:1.4rem;">Related Products</p>
        <br>
        <div class = "img-select">
          {% for similar in related %}
          <div class = "img-item">
            <a href = "{% url 'products:detail' str=similar.name %}" >
              <img src = "{{similar.image.url}}" alt = "shoe image">
            </a>
          </div>
         
          {% endfor %}
        </div>
      </div>
      <!-- card right -->
      <div class = "product-content">
        <h2 class = "product-title">{{product.name}}</h2>
        <div class = "product-rating">
            <img src="{{product.starURL}}" alt="">
          <span>Rating: {{product.imageURL}}</span>
        </div>

        <div class = "product-price">
          <p class = "new-price">Price: <span>${{product.price|floatformat:2}}</span></p>
        </div>

        <div class = "product-detail">
          <h2>about this item: </h2>
          <p>{{product.description}}</p>

          <ul>
            <li>Color: <span>{{product.appearance}}</span></li>
            {% if product.available %}
            <li>Available: <span>in stock</span></li>
            {% endif %}
            <li>Category: <span>{{product.category}}</span></li>
            <li>Shipping Area: <span>Ghana</span></li>
            <li>Shipping Fee: <span>Free</span></li>
          </ul>
        </div>

        <div class = "purchase-info">
          <button data-product={{product.id}} data-action="add" type="button" value="{{product.id}}" id="add_cart" class = "btn update-cart bg-warning text-dark">
            Add to Cart <i class = "fas fa-shopping-cart"></i>
          </button>
          <a class="btn bg-warning" href="{% url 'products:cart' %}">Cart</a>
          {% comment %} <button type = "button" class = "btn">Compare</button> {% endcomment %}
        </div>

      </div>
    </div>
  </div>

  <br><br><br>
{% endblock  %}

{% block script %}
<script >
    const imgs = document.querySelectorAll('.img-select a');
    const imgBtns = [...imgs];
    let imgId = 1;

    imgBtns.forEach((imgItem) => {
        imgItem.addEventListener('click', (event) => {
            event.preventDefault();
            imgId = imgItem.dataset.id;
            slideImage();
        });
    });

    function slideImage(){
        const displayWidth = document.querySelector('.img-showcase img:first-child').clientWidth;

        document.querySelector('.img-showcase').style.transform = `translateX(${- (imgId - 1) * displayWidth}px)`;
    }

    window.addEventListener('resize', slideImage);
</script>
{% endblock  %}

products/templates/product_page/favourite.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Favourite{% endblock  %}
{% block css %}
<link rel="stylesheet" href="{% static 'styles/shared/general.css' %}">
<link rel="stylesheet" href="{% static 'styles/shared/amazon-header.css' %}">
<link rel="stylesheet" href="{% static 'styles/pages/orders.css' %}">
{% endblock  %}

{% block content %}

<div class="main">
  <div class="page-title">Favourite List</div>
  {% for item in items %}
  <div class="orders-grid">
    <div class="order-container">
      
      <div class="order-header">
        <div class="order-header-left-section">
          <div class="order-date">
            <div class="order-header-label">Order Placed:</div>
            <div>{{item.date_added}}</div>
          </div>
          <div class="order-total">
            <div class="order-header-label">Price:</div>
            <div>${{item.product.price|floatformat:2}}</div>
          </div>
        </div>

        <div class="order-header-right-section">
          <div class="order-header-label">Order ID:</div>
          <div>{{item.id}}</div>
        </div>
      </div>

      <div class="order-details-grid">

        <div class="product-image-container">
          <img src="{{item.product.imageURL}}">
        </div>

        <div class="product-details">
          <div class="product-name">
            {{item.product.name}}
          </div>

          <div class="product-quantity">
            Quantity: {{item.quantity}}
          </div>
          <button class="buy-again-button button-primary">
            <img class="buy-again-icon" src="{% static 'images/icons/buy-again.png' %}">
            <span class="buy-again-message  update-cart"  data-product={{item.product.id}} data-action="add" >Buy it again</span>
          </button>
          <br>
          <button class="buy-again-button button-primary">
            <img class="buy-again-icon" src="{% static 'images/icons/buy-again.png' %}">
            <span class="buy-again-message  update-cart"  data-product={{item.product.id}} data-action="delete" >Remove</span>
          </button>
        </div>

        <div class="product-actions">
          <a href="{% url 'products:cart' %}">
            <button class="track-package-button button-secondary">
              cart
            </button>
          </a>
        </div>
        
      </div>
    </div>
  </div>
  {% endfor %}

</div>

{% endblock  %}

products/templates/product_page/index.html
{% extends "layout.html" %}

{% block title %} Amazon Project {% endblock  %}

{% block content %}
      
    <div class="main">
        <div class="products-grid js-product-grid">
          {% for product in products %}  
          <div class="product-container">
            <div class="product-image-container">
              <img class="product-image"
                src="{{product.imageURL}}" title="{{product.name}}">
            </div>

            <div class="product-name limit-text-to-2-lines">
              {{product.name}}
            </div>

            <div class="product-rating-container">
              <img class="product-rating-stars"
                src="{{product.starURL}}"/>
              <div class="product-rating-count link-primary">
                {{product.rating}}
              </div>
            </div>

            <div class="product-price">
              ${{product.price|floatformat:2}}
            </div>

            <div class="product-quantity-container">
              
            </div>

            <div class="product-spacer"></div>

            <div class="added-to-cart">
              <img src="images/icons/checkmark.png">
              Added
            </div>

            <button data-product={{product.id}} data-action="add" type="button" value="{{product.id}}" id="add_cart" class="add-to-cart-button button-primary update-cart" >
              Add to Cart
            </button>
            <a class="btn" href="{% url 'products:detail' str=product.name %}">Details</a>
          </div>
          {% endfor %}
        </div>
      </div>


{% endblock  %}