amazon_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('users/',include('custom_user.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

custom_user/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register_view, name="register"),
    path('login/',views.login_view, name="login"),
    path('logout/',views.logout_view, name="logout"),
    path('reg_detail/',views.register_detail, name="reg_detail"),
    path('mail/',views.send_mail,name="send_mail")
    
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('',views.index, name='index'),
    path('cart/',views.cart, name='cart'),
    path('search/', views.search, name= 'search'),
    path('checkout/',views.checkout, name="checkout"),
    path('update_item/', views.updateItem,name='update_item'),
    path('process_order/', views.processOrder,name='process_order'),
    path('contact_us/', views.contact_us,name='contact_us'),
    path('favourite/', views.favourite,name='favourite'),
    path('contact_me/',views.contact_me,name='contact_me'),
    path('about/',views.about,name='about'),
    path('our_service/',views.our_service,name='our_service'),
    path('detail_of/<str:str>', views.detail,name='detail'),
    # path('add-to-cart/<int:product_id>/',views.add_to_cart,name='add_to_cart')
]

custom_user/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True,blank=True)
    name =models.CharField(max_length=200, null=True)
    email=models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=200,null=True)
    appearance = models.CharField(max_length=100,null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True,blank=False)
    image = models.ImageField(null=True,blank=True)
    star = models.ImageField(null=True,blank=True)
    rating = models.FloatField()
    available = models.BooleanField(default=True, null=True,blank=False)
    category = models.CharField(max_length=100,null=True)
    description = models.TextField(max_length=700,null=True)


    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
    @property
    def starURL(self):
        try:
            url = self.star.url
        except:
            url = ''
        return url

class Order(models.Model):
    transaction_id = models.CharField(max_length=80,null=True)
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False,null=True,blank=False)

    def __str__(self) -> str:
        return str(self.id)
    
    # @property
    # def shipping(self):
    #     shipping = False
    #     orderitems = self.orderitem_set.all()
    #     for i in orderitems:
    #         if i.product.digital == False:
    #             shipping == True
    #     return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    

class OrderItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL, blank=True, null=True)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    username = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    region = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    payment_method = models.CharField(max_length=200, null=True)
    name_card = models.CharField(max_length=100,null=True)
    card_number = models.IntegerField(null=True)
    expiration = models.CharField(max_length=90,null=True)
    cvv = models.CharField(max_length=90,null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username
    

class Contact_us(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, blank=True, null=True)
    full_name = models.CharField(max_length=100,null=True)
    email_address = models.CharField(max_length=100,null=True)
    mobile = models.CharField(max_length=100,null=True)
    email_subject = models.CharField(max_length=100,null=True)
    messasge_info = models.CharField(max_length=100,null=True)

custom_user/forms.py
from django import forms
from products import models

class MakeDetail(forms.ModelForm):
    class Meta:
        model = models.Customer
        fields = ['name', 'email']

custom_user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.http import HttpResponse
from django.core.mail import send_mail
from django.views.generic import CreateView
from django.urls import reverse_lazy
from . import forms
from django.contrib.auth.decorators import login_required




# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request,form.save())
            return redirect('users:reg_detail')
    else:
        form = UserCreationForm()
    return render(request,'users/register.html',{'form':form})

def register_detail(request):
    if request.method == 'POST':
        form = forms.MakeDetail(request.POST)
        if form.is_valid():
            detail = form.save(commit=False)
            detail.user = request.user
            detail.save()
            return redirect('products:index')
    else:    
        form = forms.MakeDetail()
    return render(request,'users/reg_detail.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('products:index')
    else:
        form = AuthenticationForm()
    return render(request,'users/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('products:index')
    
def simple_mail(request):
    send_mail(
        subject='That is  the subject',
        message='That is my message',
        from_email='jonesmichaelfordjour2@gmail.com',
        recipient_list=['franciskwadwofordjour@gmail.com']
    )
    return HttpResponse('Message sent')

#admin lite

custom_user/templates/users/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a class="back" href="{% url 'products:index' %}">Back</a>

   <div class="wrapper">
    <h1>LOGIN</h1>
    <form class='form' action="" method='post'>
        {% csrf_token %}
        {{form.as_p}}
    
    <a href="#" class="forgot">Forgot password</a>

    
  </p>
        <input class="btn" type="submit" value="Login">
    <p class="register_link"> Dont't you have an account: <a href="{% url 'users:register' %}">Register</a></p>
    </form>
   </div>
   <style>
    *{
        padding:0;
        margin:0;
        box-sizing:border-box;
        font-family:sans-serif;
    }

    body{
        display:flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background:url({% static 'images/amazon-mobile-logo.png' %}) ;

    }
    .back{
        text-decoration: none;
        background-color: orange;
        color:black;
        border-radius: 6px;
        margin: 30px;
        width: 100px;
        height: 40px;
        text-align: center;
        padding-top:9px;
        position:absolute;
        top: 0;
        left: 0;

    }
    .wrapper{
        width: 420px;
        background: transparent;
        border: 2px solid rgba(255,255,255,.3);
        backdrop-filter: blur(10px);
        border-radius: 12px;
        padding: 30px 40px;
    }

    h1{
        font-size:36px;
        text-align: center;
        color:#f48c15;
    }

    #id_username,#id_password{
        width: 100%;
        height: 50px;
        background-color: yellow;
        margin: 30px 0;
        border:none;
        outline:none;
        border: 2px solid rgba(255,255,255,.2);
        border-radius:10px;
    }

    form label{
        padding:10px;
        font-size: 1.6rem;
    }

    .wrapper .forgot{
        display: flex;
        justify-content: space-between;
        font-size: 16.5px;
        margin:-15px 0 15px;
        color:#f48c15;
        text-decoration: none;

    }

   .forgot a:hover{
        text-decoration: underline;
    }

    .wrapper .btn{
        width: 100%;
        height: 45px;
        background:#fff ;
        border: none;
        outline: none;
        border-radius: 40px;
        box-shadow: 0 0 10px rgba(0,0,0, .1);
        cursor:pointer;
        color: #333;
        font-weight:600;

    }

    .wrapper .register_link{
        font-size: 14.5px;
        text-align: center;
        margin-top:20px;
    }

    .register_link  a{
        color:#f07706;
        text-decoration:none;
        font-weight:600;
        
    }
    .register_link  a:hover{
        text-decoration: underline;
    }
</style>
</body>
</html>

custom_user/templates/users/reg_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <h1>Fill this form</h1>
        <form action="{% url 'users:reg_detail' %}"  method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn">Submit</button>
        </form>
    </div>
</body>
<style>
    *{
        padding:0;
        margin:0;
        box-sizing:border-box;
        font-family:sans-serif;
    }

    body{
        display:flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background:url({% static 'images/amazon-mobile-logo.png' %}) ;

    }

    .wrapper{
        width: 420px;
        background: transparent;
        border: 2px solid rgba(255,255,255,.3);
        backdrop-filter: blur(10px);
        border-radius: 12px;
        padding: 30px 40px;
    }

    h1{
        font-size:36px;
        text-align: center;
        color:#f48c15;
    }

    #id_email,#id_name{
        width: 100%;
        height: 50px;
        background-color: yellow;
        margin: 30px 0;
        border:none;
        outline:none;
        border: 2px solid rgba(255,255,255,.2);
        border-radius:10px;
    }

    form label{
        padding:10px;
        font-size: 1.6rem;
    }



    .wrapper .btn{
        width: 100%;
        height: 45px;
        background:#fff ;
        border: none;
        outline: none;
        border-radius: 40px;
        box-shadow: 0 0 10px rgba(0,0,0, .1);
        cursor:pointer;
        color: #333;
        font-weight:600;

    }



</style>
</html>

custom_user/templates/users/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <a class="back" href="{% url 'products:index' %}">Back</a>

    <div class="wrapper">
        <h1>Register</h1>
        <form action="{% url "users:register" %}" method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button>Submit</button>
        </form>
    
        </div>
        <br><br><br>
        <style>
            *{
                padding:0;
                margin: 0;
                box-sizing: border-box;
                font-family: sans-serif;
            }
        
            body{
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                background:url({% static 'images/amazon-logo.png' %}) ;
        
            }

            .back{
                text-decoration: none;
                background-color: rgb(162, 172, 13);
                color:rgb(0, 0, 0);
                border-radius: 6px;
                font-size: 1.4rem;
                border-radius: 6px;
                margin: 30px;
                width: 100px;
                height: 40px;
                text-align: center;
                padding-top:9px;
                position:absolute;
                top: 0;
                left: 0;
        
            }
        
            .wrapper{
                width: 420px;
                background: transparent;
                border: 2px solid rgba(0, 0, 0, 0.3);
                backdrop-filter: blur(10px);
                border-radius: 12px;
                padding: 30px 40px;
        
            }
        
            h1{
                font-size:36px;
                text-align: center;
            }
        
            #id_username,#id_password2,#id_password1{
                width: 100%;
                height: 30px;
                background-color: rgb(255, 162, 0);
                margin: 20px 0;
                border:none;
                outline:none;
                border: 2px solid rgba(255,255,255,.2);
                border-radius:10px;
            }
        
            form label{
                padding:10px;
                font-size: 1.6rem;
            }
        
            .wrapper button{
                width: 100%;
                height: 45px;
                background:#fff ;
                border: none;
                outline: none;
                border-radius: 40px;
                box-shadow: 0 0 10px rgba(0,0,0, .1);
                cursor:pointer;
                color: #333;
                font-weight:600;
        
            }
        </style>
    
</body>
</html>