amazon_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('users/',include('custom_user.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

custom_user/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register_view, name="register"),
    path('login/',views.login_view, name="login"),
    path('logout/',views.logout_view, name="logout"),
    path('reg_detail/',views.register_detail, name="reg_detail"),
    path('mail/',views.send_mail,name="send_mail")
    
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('',views.index, name='index'),
    path('cart/',views.cart, name='cart'),
    path('search/', views.search, name= 'search'),
    path('checkout/',views.checkout, name="checkout"),
    path('update_item/', views.updateItem,name='update_item'),
    path('process_order/', views.processOrder,name='process_order'),
    path('contact_us/', views.contact_us,name='contact_us'),
    path('favourite/', views.favourite,name='favourite'),
    path('contact_me/',views.contact_me,name='contact_me'),
    path('about/',views.about,name='about'),
    path('our_service/',views.our_service,name='our_service'),
    path('detail_of/<str:str>', views.detail,name='detail'),
    # path('add-to-cart/<int:product_id>/',views.add_to_cart,name='add_to_cart')
]

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>{% block title %} App title{% endblock  %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/shared/general.css' %}">
    <link rel="stylesheet" href="{% static 'styles/shared/amazon-header.css' %}">
    <link rel="stylesheet" href=" {% static 'styles/pages/amazon.css' %}">
    <link rel="icon" href="{% static 'images/amazon-logo-white.png' %}">
    {% block css %}{% endblock  %}
    <script type='text/javascript'>var user = '{{request.user}}'
        function getToken(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
        }
        let csrftoken = getToken('csrftoken');
    </script>
    <link rel="stylesheet" href="/static/styles/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    {% block unique %}{% endblock  %}
  </head>
  <body>
    <div class="amazon-header">
      <div class="amazon-header-left-section">
        <a href="{% url "products:index" %}" class="header-links">
          <img class="amazon-logo"
            src="{% static 'images/amazon-logo-white.png' %}">
          <img class="amazon-mobile-logo"
            src="{% static 'images/amazon-mobile-logo-white.png' %}">
        </a>
      </div>

      <form action="{% url "products:search" %}" method=POST style="width:100%;">
        {% csrf_token %}
        <div class="amazon-header-middle-section">
          <input class="search-bar" type="text" placeholder="Search" name="searched">

          <button class="search-button">
            <img class="search-icon" src=" {% static 'images/icons/search-icon.png' %}">
          </button>
        </div>
      </form >
      <div class="amazon-header-right-section">
        <a class="orders-links header-links" href="{% url 'products:favourite' %}">
          <span class="returns-text">Favourite</span>
          <span class="orders-text"> List</span>
        </a>
        <a class="cart-link header-links" href="{% url 'products:cart' %}">
          <img class="cart-icon" src="{% static 'images/icons/cart-icon.png' %}">
          <div class="cart-quantity js-cart-quantity">{{cartItems}}</div>
          <div class="cart-text">Cart</div>
        </a>
      </div>
    </div>
    {% block content %}
    
    {% endblock  %}
      <footer class="footers">
        <div class="container1">
            <div class="row1">
                <div class="footer-col">
                    <h4>company</h4>
                    <ul>
                        <li><a href="{% url 'products:about' %}">About us</a></li>
                        <li><a href="{% url 'products:our_service' %}">Our services</a></li>
                        <li><a href="{% url 'products:index' %}">Home</a></li>
                        <li><a href="{% url 'products:contact_me' %} ">Contact Us</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>get help</h4>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="{% url 'products:checkout' %}">Shipping</a></li>
                        <li><a href="{% url 'products:cart' %}">order status</a></li>
                        <li><a href="{% url 'products:checkout' %}">payment options</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>online shop</h4>
                    <ul>
                        <li><a href="http://127.0.0.1:8000/detail_of/Women's%20Chiffon%20Beachwear%20Cover%20Up%20-%20Black">Cloth</a></li>
                        <li><a href="http://127.0.0.1:8000/detail_of/2%20Slot%20Toaster%20-%20Black">Home appliance</a></li>

                        {% if user.is_authenticated %}
                        <li><form action="{% url 'users:logout' %}" method='post'>
                          {% csrf_token %}
                          <button class="btn btn-dark">Logout</button>
                        </form></li>
                        <li><a href="{% url 'products:checkout' %}">Checkout</a></li>
                        {% else %}
                        <li><a href="{% url 'users:register' %}">Register</a></li>
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>follow us</h4>
                    <div class="social-links">
                        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                        </svg></a>
                        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                          <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                        </svg></i></a>
                        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                          <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                        </svg></a>
                        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
                          <path d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232"/>
                        </svg></a>
                    </div>
                </div>
            </div>
          </div>
      </footer>
  </body>
<script type="text/javascript" src="{% static 'scripts/cart.js' %}"></script>

  {% block script %}{% endblock  %}
</html>